name: TryOn
description: Virtually Try-On OutFits.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  firebase_core: ^2.24.2
  dio: ^5.4.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.5

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo/logo-noname.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo/logo-noname.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo/logo-noname.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo/logo-noname.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/logo/logo-padding.png"
  android_12:
    color: "#ffffff"
    image: "assets/images/logo/logo-padding.png"
  fullscreen: true

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
