name: TryOn
description: "Virtually Try-On OutFits"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  firebase_core: ^2.24.2
  dio: ^5.4.0
  smooth_page_indicator: ^1.1.0
  fluttertoast: ^8.2.4
  flutter_otp_text_field: ^1.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_screenutil: ^5.9.0
  get_it: ^7.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.5

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo/logo-noname.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo/logo-noname.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo/logo-noname.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo/logo-noname.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/logo/logo-padding.png"
  android_12:
    color: "#ffffff"
    image: "assets/images/logo/logo-padding.png"
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/logo/
    - assets/images/onboarding/
