// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUcJZs-oXGcjwqNYfeSWG_Y1UjEobEAmo',
    appId: '1:757018841154:web:a254f7f7410a7f0f5e5ddb',
    messagingSenderId: '757018841154',
    projectId: 'try-on-graduation-project',
    authDomain: 'try-on-graduation-project.firebaseapp.com',
    storageBucket: 'try-on-graduation-project.appspot.com',
    measurementId: 'G-NEQBFD2NEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0A60ON2TPB7Zrkgf9NU-nosqiPlKSSyM',
    appId: '1:757018841154:android:328aff77a636c6615e5ddb',
    messagingSenderId: '757018841154',
    projectId: 'try-on-graduation-project',
    storageBucket: 'try-on-graduation-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQgCiPKCjCWtxhrlKuL6LHfcltmC4WviM',
    appId: '1:757018841154:ios:a167091f0c8096905e5ddb',
    messagingSenderId: '757018841154',
    projectId: 'try-on-graduation-project',
    storageBucket: 'try-on-graduation-project.appspot.com',
    iosBundleId: 'com.magic.prova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQgCiPKCjCWtxhrlKuL6LHfcltmC4WviM',
    appId: '1:757018841154:ios:eed67b7f01b32f125e5ddb',
    messagingSenderId: '757018841154',
    projectId: 'try-on-graduation-project',
    storageBucket: 'try-on-graduation-project.appspot.com',
    iosBundleId: 'com.magic.prova.RunnerTests',
  );
}
